reply comment
meathill/awesome-comment pull request #16
Opened 2023-08-24 15:14 UTC by bambooom

- feat: can set parent_id and ancestor_id when post comment.
- feat: change comments structure and post comment.
- fix: tweaks to fix when posting new comments.

2023-08-25 02:36 UTC, meathill requested changes

2023-08-25 02:36 UTC, meathill commented on packages/admin/pages/examples/preload.vue
> +    'https://www.arealme.com/eq/en/',
测试数据不要改。

2023-08-25 02:36 UTC, meathill commented on packages/admin/server/api/comment.post.ts
> +        ancestor_id: body.ancestorId || -1,
这里我们用 0 吧，-1 大部分时间会被判定为 `true`

2023-08-25 02:36 UTC, meathill commented on packages/awesome-comment/src/components/comment-item.vue
> +          :title="comment.createdAt"
`title` 应该 formatTime 一下

2023-08-25 02:36 UTC, meathill commented on packages/awesome-comment/src/components/comment-item.vue
> +        svg(xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 bi bi-reply-fill" fill="none" stroke="currentColor" viewBox="0 0 16 16")
svg 不要放模版里，用 unpkg 上的 bootstrap-icons 或其它图标库即可。

2023-08-25 02:36 UTC, meathill commented on packages/awesome-comment/src/main.ts
> +  app.provide('postId', 'https://www.arealme.com/eq/en/');
Ditto.

2023-08-25 02:36 UTC, meathill commented on packages/awesome-comment/src/store/index.ts
> +    if ((ancestorId && ancestorId > 0) || (parentId && parentId > 0)) {
-1 就会有这些问题，为什么不能直接用 0 呢？

2023-08-25 12:31 UTC, meathill requested changes

2023-08-25 12:31 UTC, meathill commented on packages/awesome-comment/src/components/comment-item.vue
> +        i.bi.bi-reply-fill.h-4.w-4
这会导致一个问题，我们编译的时候不会把 bootstrap-icons 打包进来，所以用户本地是看不到这个图标的。

我之前的意思是用 https://unpkg.com/bootstrap-icons@1.10.5/icons/reply-fill.svg 这样的方式来引用。至于颜色可以用 css 颜色滤镜来修改。

2023-08-28 14:48 UTC, meathill requested changes

2023-08-28 14:48 UTC, meathill commented on packages/admin/server/api/comments.get.ts
> +    const url = `https://ap-northeast-1.data.tidbcloud.com/api/v1beta/app/dataapp-NFYbhmOK/endpoint/v1/fetch?post_id=${postId}&start=${start}`;
这里最好不要 API 名称，直接改版本号就好了。

2023-08-28 14:48 UTC, meathill commented on packages/awesome-comment/src/store/index.ts
> +    const res = from.filter(item => !item.ancestor_id || Number(item.ancestor_id) === 0).map(formatHelper);
为什么要这样？有脏数据？

2023-08-28 14:48 UTC, meathill commented on packages/awesome-comment/src/store/index.ts
> +    const deeper = from.filter(item => item.ancestor_id && Number(item.ancestor_id) > 0);
最好一遍循环出来，虽然只有几十条，但是反复遍历不是个好习惯。

你可以一边循环，一遍把评论放到一个 map 里，然后后面就好找了。

2023-08-28 14:48 UTC, meathill commented on packages/awesome-comment/src/store/index.ts
> +    if (ancestorId || parentId) {
这里也一样，我们可以在 `comments.value` 里面存 `Record<id extend number, Comment>`，然后后面无论怎么添加，都很容易放进去了。当然，开头插入新评论会比较难搞。

2023-08-28 14:48 UTC, meathill commented on packages/awesome-comment/src/components/comment-item.vue
> +  :class="{'animated flash': comment.isNew}"
缺了一个 id，我之前提过。麻烦加上，方便做锚点跳转。

2023-08-28 15:09 UTC, bambooom commented on packages/admin/server/api/comments.get.ts
> +    const url = `https://ap-northeast-1.data.tidbcloud.com/api/v1beta/app/dataapp-NFYbhmOK/endpoint/v1/fetch?post_id=${postId}&start=${start}`;
这个是新加的一个endpoint，想的是测试没问题的话再改一下旧的SQL，这里不需要变动

2023-08-28 15:10 UTC, bambooom commented on packages/awesome-comment/src/store/index.ts
> +    const res = from.filter(item => !item.ancestor_id || Number(item.ancestor_id) === 0).map(formatHelper);
对，旧的数据里 ancestor_id 是空值，新插入的第一级评论 ancestor_id 才是 0

2023-08-29 06:37 UTC, meathill requested changes
我好像没有看到指向“reply to”的链接？

2023-08-29 06:37 UTC, meathill commented on packages/awesome-comment/src/store/index.ts
> +      }
这里不需要往中间插入，只要时间顺序就好，类似知乎的做法。然后我们加入锚点跳转即可。

2023-08-30 15:59 UTC, meathill approved these changes

2023-08-30 15:59 UTC, meathill commented on packages/awesome-comment/src/components/comment-item.vue
> +  if (props.ancestorId) {
一般我们先写短的，比如 `if (!props.ancestorId) return ''`。

2023-08-30 16:00 UTC, merged